name: 'Promote an API in wM API Gateway'
description: 'Promote an API to a given stage in webMethods API Gateway.'
branding:
  icon: 'lock'
  color: 'blue'
inputs:
  apigw-url: 
    description: 'The url of your API Gateway instance.'
    required: true
  apigw-username:
    description: 'The API Gateway user to execute this action with.'
    required: true
  apigw-password:
    description: 'The password for the API Gateway user to execute this action with.'
    required: true
  api-name:
    description: 'The name of the API to promote.'
    required: true
  api-version:
    description: 'The version of the API to promote.'
    required: true
  stage-name:
    description: 'The name of the stage to promote the API to.'
    required: true
  debug:
    description: 'Use debug logging. Default is false.'
    required: false
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'